SPHINX_PROJECT_NAME=SPI Component
VERSION=2.0
DOXYGEN_DIRS=../../sc_spi/module_spi_master ../../sc_spi/module_spi_slave
SOURCE_INCLUDE_DIRS=../../sc_spi
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
