SPHINX_PROJECT_NAME=xSOFTip SPI Master Library
VERSION=1.0
DOXYGEN_DIRS=../../../sc_spi/module_spi_master 
SOURCE_INCLUDE_DIRS=../../../sc_spi
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
